from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any


def _copy_tree(source: Path, destination: Path) -> None:
    if not source.exists():
        return
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)


def build_huggingface_bundle(
    *,
    canonical_dir: Path,
    destination: Path,
    reports_dir: Path | None = None,
    include_models_from: Path | None = None,
) -> dict[str, Any]:
    canonical_dir = Path(canonical_dir).resolve()
    destination = Path(destination).resolve()
    manifest_path = canonical_dir / "dataset_manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Canonical manifest is missing: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    destination.mkdir(parents=True, exist_ok=True)
    _copy_tree(canonical_dir, destination / "canonical")
    if reports_dir:
        _copy_tree(Path(reports_dir), destination / "reports")
    if include_models_from:
        _copy_tree(Path(include_models_from), destination / "models")

    metrics = manifest.get("metrics", {})
    splits = manifest.get("split_counts_steps", {})
    card = f'''---
pretty_name: REACTS USPTO-LLM Multistep Canonical Dataset
license: other
task_categories:
- text-classification
- feature-extraction
- tabular-classification
tags:
- chemistry
- reactions
- patents
- uspto
- cheminformatics
---

# REACTS USPTO-LLM Multistep Canonical Dataset

This publication bundle contains the canonical, quality-annotated dataset generated by REACTS Product One from the user-provided USPTO-LLM multistep artifact.

## Scale

- Steps: **{metrics.get('steps_total', 'unknown')}**
- Routes: **{metrics.get('routes_total', 'unknown')}**
- Parse-valid steps: **{metrics.get('steps_parse_valid', 'unknown')}**
- Symbolic-intermediate steps: **{metrics.get('steps_symbolic_intermediate', 'unknown')}**
- Storage format: **{manifest.get('storage_format', 'unknown')}**
- Train/validation/test steps: **{splits.get('train', 0)} / {splits.get('val', 0)} / {splits.get('test', 0)}**

## Contracts

- Source values are immutable.
- Training-safe condition values are separate from observed values.
- Patent documents do not cross benchmark partitions.
- Symbolic route intermediates are retained as partial structural records.
- Quality events explain exclusions and repairs.

## Intended use

Reaction-data curation research, parse-failure modeling, patent reaction retrieval, condition classification, route analytics, and reproducible ML benchmarking.

## Limitations

The dataset is patent-derived and label-noisy. It does not contain validated yields or reaction-success labels. Model outputs derived from it are not experimental validation or laboratory instructions.
'''
    (destination / "README.md").write_text(card, encoding="utf-8")
    (destination / ".gitattributes").write_text(
        "*.parquet filter=lfs diff=lfs merge=lfs -text\n*.joblib filter=lfs diff=lfs merge=lfs -text\n*.npz filter=lfs diff=lfs merge=lfs -text\n",
        encoding="utf-8",
    )
    release_manifest = {
        "dataset_version": manifest.get("dataset_version"),
        "source_manifest_sha256": manifest.get("source", {}).get("checksum_sha256"),
        "storage_format": manifest.get("storage_format"),
        "included_models": bool(include_models_from),
        "canonical_manifest": "canonical/dataset_manifest.json",
    }
    (destination / "release_manifest.json").write_text(json.dumps(release_manifest, indent=2), encoding="utf-8")
    return {"destination": str(destination), **release_manifest}
